export const getPointExchange = () => {
  return {
    code: 200,
    data: [
      {
        groupKey: '注册会员即有机会兑换',
        groupImg: '1.jpg',
        groupSeq: '1',
        items: [
          {
            id: 21,
            mpId: 'harbin',
            activityCode: 'IQMS20240315C000004',
            mechanismCode: 'IQMS20240315M000007',
            prizeCode: 'IQMS20240326P000001',
            prizeName: 'NBA壁纸',
            betNum: 1,
            originalBetNum: 1,
            betLimit: 1,
            unlockCondition: 0,
            prizeImg: 'https://front-static-c.ab-inbev.cn/brand/20240930/pic_bizhi01.png',
            prizeDesc: '以NBA 元素为设计核心的jpg手机壁纸',
            exchangeDesc: 'https://front-static-c.ab-inbev.cn/brand/20240815/pic_NABbizhi_detail@2x.png',
            configJson: null,
            stock: 89,
            locked: false,
            overLimit: true,
            groupKey: '注册会员即有机会兑换',
            groupImg: '1.jpg',
            groupSeq: '1',
            seq: 1,
            userExchangeState: 3,
            type: 2,
            subType: 26,
            specialType: 1,
            deleted: false,
            createTime: 1709878181000,
            updateTime: 1728443940000,
          },
          {
            id: 22,
            mpId: 'harbin',
            activityCode: 'IQMS20240315C000004',
            mechanismCode: 'IQMS20240315M000007',
            prizeCode: 'IQMS20240315P000003',
            prizeName: '红包封面',
            betNum: 5,
            originalBetNum: 5,
            betLimit: 1,
            unlockCondition: 0,
            prizeImg: 'https://front-static-c.ab-inbev.cn/brand/20240930/pic_hongbao01.png',
            prizeDesc: '红包封面-联名款',
            exchangeDesc: 'https://front-static-c.ab-inbev.cn/brand/20240815/d67fgvviie-pic_hongbao_detail@2x.png',
            configJson: null,
            stock: 60,
            locked: false,
            overLimit: true,
            groupKey: '注册会员即有机会兑换',
            groupImg: '1.jpg',
            groupSeq: '1',
            seq: 5,
            userExchangeState: 3,
            type: 2,
            subType: 27,
            specialType: 2,
            deleted: false,
            createTime: 1709878181000,
            updateTime: 1728715018000,
          },
        ],
      },
      {
        groupKey: '开盖扫码1次解锁',
        groupImg: '1.jpg',
        groupSeq: '2',
        items: [
          {
            id: 32,
            mpId: 'harbin',
            activityCode: 'IQMS20240315C000004',
            mechanismCode: 'IQMS20240315M000007',
            prizeCode: 'IQMS20240911P000001',
            prizeName: '高德打车5元代金券',
            betNum: 4,
            originalBetNum: 4,
            betLimit: 1,
            unlockCondition: 1,
            prizeImg: 'https://front-static-c.ab-inbev.cn/brand/20240930/pic_gaode01.png',
            prizeDesc: '高德打车5元代金券兑换码',
            exchangeDesc: 'https://front-static-c.ab-inbev.cn/brand/20240815/9r4lrtrnmt-pic_gaode_detail@2x.png',
            configJson: null,
            stock: 98,
            locked: true,
            overLimit: true,
            groupKey: '开盖扫码1次解锁',
            groupImg: '1.jpg',
            groupSeq: '2',
            seq: 4,
            userExchangeState: 2,
            type: 1,
            subType: 26,
            specialType: null,
            deleted: false,
            createTime: 1709878181000,
            updateTime: 1728715018000,
          },
          {
            id: 30,
            mpId: 'harbin',
            activityCode: 'IQMS20240315C000004',
            mechanismCode: 'IQMS20240315M000007',
            prizeCode: 'IQMS20240315P000004',
            prizeName: '腾讯体育NBA单场观塞券',
            betNum: 20,
            originalBetNum: 20,
            betLimit: 1,
            unlockCondition: 1,
            prizeImg: 'https://front-static-c.ab-inbev.cn/brand/20240930/pic_guansaiquan01.png',
            prizeDesc: '腾讯体育观赛券，可在腾讯体育兑换一场比赛观看权',
            exchangeDesc: 'https://front-static-c.ab-inbev.cn/brand/20240815/oyqic7jjay-pic_guansaiquan_detail@2x.png',
            configJson: null,
            stock: 86,
            locked: true,
            overLimit: true,
            groupKey: '开盖扫码1次解锁',
            groupImg: '1.jpg',
            groupSeq: '2',
            seq: 20,
            userExchangeState: 2,
            type: 2,
            subType: 26,
            specialType: null,
            deleted: false,
            createTime: 1709878181000,
            updateTime: 1729070479000,
          },
        ],
      },
      {
        groupKey: '开盖扫码2次解锁',
        groupImg: '1.jpg',
        groupSeq: '3',
        items: [
          {
            id: 33,
            mpId: 'harbin',
            activityCode: 'IQMS20240315C000004',
            mechanismCode: 'IQMS20240315M000007',
            prizeCode: 'IQMS20240911P000002',
            prizeName: '腾讯视频VIP周卡',
            betNum: 7,
            originalBetNum: 7,
            betLimit: 1,
            unlockCondition: 2,
            prizeImg: 'https://front-static-c.ab-inbev.cn/brand/20240930/pic_tengxunzhouka01.png',
            prizeDesc: '腾讯视频VIP周卡兑换码',
            exchangeDesc:
              'https://front-static-c.ab-inbev.cn/brand/20240815/deot3li0do-pic_tengxunzhouka01_detail@2x.png',
            configJson: null,
            stock: 98,
            locked: true,
            overLimit: false,
            groupKey: '开盖扫码2次解锁',
            groupImg: '1.jpg',
            groupSeq: '3',
            seq: 7,
            userExchangeState: 2,
            type: 1,
            subType: 26,
            specialType: null,
            deleted: false,
            createTime: 1709878181000,
            updateTime: 1728728728000,
          },
          {
            id: 24,
            mpId: 'harbin',
            activityCode: 'IQMS20240315C000004',
            mechanismCode: 'IQMS20240315M000007',
            prizeCode: 'IQMS20240315P000013',
            prizeName: '哔哩哔哩大会员月卡',
            betNum: 60,
            originalBetNum: 60,
            betLimit: 1,
            unlockCondition: 2,
            prizeImg: 'https://front-static-c.ab-inbev.cn/brand/20240930/pic_bilibli01.png',
            prizeDesc: '哔哩哔哩大会员月卡兑换券',
            exchangeDesc: 'https://front-static-c.ab-inbev.cn/brand/20240815/pic_bibi01_detail@2x.png',
            configJson: null,
            stock: 91,
            locked: true,
            overLimit: true,
            groupKey: '开盖扫码2次解锁',
            groupImg: '1.jpg',
            groupSeq: '3',
            seq: 60,
            userExchangeState: 2,
            type: 2,
            subType: 26,
            specialType: null,
            deleted: false,
            createTime: 1709878181000,
            updateTime: 1728715018000,
          },
        ],
      },
      {
        groupKey: '开盖扫码7次解锁',
        groupImg: '1.jpg',
        groupSeq: '4',
        items: [
          {
            id: 23,
            mpId: 'harbin',
            activityCode: 'IQMS20240315C000004',
            mechanismCode: 'IQMS20240315M000007',
            prizeCode: 'IQMS20240315P000007',
            prizeName: '芒果 TV 黄金会员月卡',
            betNum: 22,
            originalBetNum: 22,
            betLimit: 1,
            unlockCondition: 7,
            prizeImg: 'https://front-static-c.ab-inbev.cn/brand/20240930/pic_mangguo01.png',
            prizeDesc: '芒果 TV 黄金会员月卡兑换券',
            exchangeDesc: 'https://front-static-c.ab-inbev.cn/brand/20240815/yzc1jcz62h-pic_mangguo01_detail@2x.png',
            configJson: null,
            stock: 84,
            locked: true,
            overLimit: false,
            groupKey: '开盖扫码7次解锁',
            groupImg: '1.jpg',
            groupSeq: '4',
            seq: 22,
            userExchangeState: 2,
            type: 2,
            subType: 26,
            specialType: null,
            deleted: false,
            createTime: 1709878181000,
            updateTime: 1728715018000,
          },
          {
            id: 27,
            mpId: 'harbin',
            activityCode: 'IQMS20240315C000004',
            mechanismCode: 'IQMS20240315M000007',
            prizeCode: 'IQMS20240315P000014',
            prizeName: '腾讯体育超级VIP月卡',
            betNum: 200,
            originalBetNum: 200,
            betLimit: 1,
            unlockCondition: 7,
            prizeImg: 'https://front-static-c.ab-inbev.cn/brand/20240930/pic_tengxunyueka01.png',
            prizeDesc: '腾讯体育超级vip月卡兑换券',
            exchangeDesc:
              'https://front-static-c.ab-inbev.cn/brand/20240815/qq0coio7vc-pic_tengxunyueka01_detail@2x.png',
            configJson: null,
            stock: 92,
            locked: true,
            overLimit: true,
            groupKey: '开盖扫码7次解锁',
            groupImg: '1.jpg',
            groupSeq: '4',
            seq: 200,
            userExchangeState: 2,
            type: 2,
            subType: 26,
            specialType: null,
            deleted: false,
            createTime: 1709878181000,
            updateTime: 1728728909000,
          },
        ],
      },
      {
        groupKey: '开盖扫码13次解锁',
        groupImg: '1.jpg',
        groupSeq: '5',
        items: [
          {
            id: 26,
            mpId: 'harbin',
            activityCode: 'IQMS20240315C000004',
            mechanismCode: 'IQMS20240315M000007',
            prizeCode: 'IQMS20240315P000006',
            prizeName: '球衣拎袋',
            betNum: 330,
            originalBetNum: 330,
            betLimit: 1,
            unlockCondition: 13,
            prizeImg: 'https://front-static-c.ab-inbev.cn/brand/20240815/%E7%90%83%E8%A1%A3%E6%8B%8E%E8%A2%8B.png',
            prizeDesc: 'NBA湖人队 ，勇士队， 菲尼克斯太阳队， 公牛队， 凯尔特人队， 热火队球衣拎袋，6种款式随机发送',
            exchangeDesc: 'https://front-static-c.ab-inbev.cn/brand/20240815/pic_qiuyi01_detail@2x.png',
            configJson: null,
            stock: 79,
            locked: true,
            overLimit: false,
            groupKey: '开盖扫码13次解锁',
            groupImg: '1.jpg',
            groupSeq: '5',
            seq: 330,
            userExchangeState: 2,
            type: 1,
            subType: 1,
            specialType: null,
            deleted: false,
            createTime: 1709878181000,
            updateTime: 1728715018000,
          },
        ],
      },
      {
        groupKey: '开盖扫码49次解锁',
        groupImg: '1.jpg',
        groupSeq: '6',
        items: [
          {
            id: 25,
            mpId: 'harbin',
            activityCode: 'IQMS20240315C000004',
            mechanismCode: 'IQMS20240315M000007',
            prizeCode: 'IQMS20240315P000005',
            prizeName: 'NBA吨吨桶',
            betNum: 340,
            originalBetNum: 340,
            betLimit: 1,
            unlockCondition: 49,
            prizeImg: 'https://front-static-c.ab-inbev.cn/brand/20240930/pic_dungdungtong01.png',
            prizeDesc: '哈尔滨啤酒与NBA联名吨吨桶1.8L',
            exchangeDesc: 'https://front-static-c.ab-inbev.cn/brand/20240815/pic_shangpinxiangqing@2x.png',
            configJson: null,
            stock: 95,
            locked: true,
            overLimit: false,
            groupKey: '开盖扫码49次解锁',
            groupImg: '1.jpg',
            groupSeq: '6',
            seq: 340,
            userExchangeState: 2,
            type: 1,
            subType: 1,
            specialType: null,
            deleted: false,
            createTime: 1709878181000,
            updateTime: 1728718100000,
          },
          {
            id: 28,
            mpId: 'harbin',
            activityCode: 'IQMS20240315C000004',
            mechanismCode: 'IQMS20240315M000007',
            prizeCode: 'IQMS20240315P000009',
            prizeName: 'NBA篮球',
            betNum: 780,
            originalBetNum: 780,
            betLimit: 1,
            unlockCondition: 49,
            prizeImg: 'https://front-static-c.ab-inbev.cn/brand/20240815/NBAlanqiu@2x.png',
            prizeDesc: '哈尔滨啤酒与NBA联名Wilson篮球',
            exchangeDesc: 'https://front-static-c.ab-inbev.cn/brand/20240815/pic_lanqiu01_detail@2x.png',
            configJson: null,
            stock: 91,
            locked: true,
            overLimit: false,
            groupKey: '开盖扫码49次解锁',
            groupImg: '1.jpg',
            groupSeq: '6',
            seq: 780,
            userExchangeState: 2,
            type: 1,
            subType: 1,
            specialType: null,
            deleted: false,
            createTime: 1709878181000,
            updateTime: 1728959043000,
          },
          {
            id: 29,
            mpId: 'harbin',
            activityCode: 'IQMS20240315C000004',
            mechanismCode: 'IQMS20240315M000007',
            prizeCode: 'IQMS20240315P000008',
            prizeName: 'NBA球衣',
            betNum: 2808,
            originalBetNum: 2808,
            betLimit: 1,
            unlockCondition: 49,
            prizeImg: 'https://front-static-c.ab-inbev.cn/brand/20240930/pic_qiuyi01.png',
            prizeDesc: 'NBA官方球队球衣',
            exchangeDesc: 'https://front-static-c.ab-inbev.cn/brand/20240815/ocf8zj6ety-pic_shuiping01_detail@2x.png',
            configJson: null,
            stock: 94,
            locked: true,
            overLimit: false,
            groupKey: '开盖扫码49次解锁',
            groupImg: '1.jpg',
            groupSeq: '6',
            seq: 2808,
            userExchangeState: 2,
            type: 1,
            subType: 1,
            specialType: null,
            deleted: false,
            createTime: 1709878181000,
            updateTime: 1728715018000,
          },
        ],
      },
    ],
    message: null,
    timestamp: 1729595958902,
  };
};
